### ISSUE TITLE
(Temporary Solution) Crash when exporting >20sec video with filter.

### ISSUE THREAD

**Issue by twomedia** [rFlex/SCRecorder#205]
@rFlex Having issues with both my implementation of SCRecorder, and the example app.

If you record a video which is longer than 30 seconds and apply a filter, the app crashes during the export due to memory constraints.

Anyone else experiencing this??
TM

**Comment by twomedia** [comment]
I'm going to try and find a solution to this, if anyone makes ground let me know.

**Comment by twomedia** [comment]
Found a temporary solution:
This crash appeared in the v2.5.0 release, rolling back "SCAssetExportSession" to v2.4.9 fixed the crash.

The issue is to do with the multithreading introduced in v2.5.0. I will try and fix this in the future and submit a pull request when/if I do. If anyone else has a solution for this I will love you forever <3

**Comment by rFlex** [comment]
I can't reproduce that bug on my iPhone 6, iOS 8.4.1. What iOS and iPhone do you have? What's the crash exactly?

**Comment by twomedia** [comment]
@rFlex I have tested on both IOS 8.4.1 and IOS 9 Beta 5 on iPhone 6 and 6+ and they are showing this issue. Only happens when you apply a filter.

**Comment by rFlex** [comment]
Can you try using the latest commit on master, uninstall the example and running it again?

**Comment by twomedia** [comment]
@rFlex Sure, give me 5 :)

**Comment by twomedia** [comment]
Clean installed the latest commit and still having the crash issue. I recorded my iPhone screen so you can see whats going on. https://www.youtube.com/watch?v=iIDTt6sjuAc

**Comment by twomedia** [comment]
Also thanks for your help mate, really appreciate it! 😊✌🏻️

**Comment by drwin** [comment]
I have the same issue. It occurs in Xcode 7 GM & iOS9 GM.  Please help me.

**Comment by rFlex** [comment]
Thank you so much @twomedia for these informations.

I upgraded my iPhone to iOS 9 and I see this issue now. Will try finding a fix asap.

**Comment by rFlex** [comment]
This has been fixed and pushed a v2.5.3 on cocoa pods. Seems like there is some changes with internal autorelease pools on dispatch queues.

Animated filters seem to leak on iOS 9 GM, won't start investigating until the final version of iOS 9 is released since it could be an iOS bug.

**Comment by YangGuanNan** [comment]
Hi @rFlex ,this issue still occur on iPone6Plus with iOS9.0.2 and SCRecorder2.5.3
