### ISSUE TITLE
Terrible Memory Leak 

### ISSUE THREAD

**Issue by fayhot** [rFlex/SCRecorder#216]
@rFlex  
There's a terrible memory leak of the SCPlayer

Reproduce the memory leak as follow:
1. recorder a segment, the long the better, 1-2 seconds is enough.
2. go to SCVideoPlayerViewController view. 
    Set the SCPlayer attribute loopEnable to be YES.
    As the filterselectorview render the video segment, the is a continuous 0.5MB/s(for my test, 1-2s time long) Memory leak for me.

Got the problem on iphone6 (iOS 9). I guess it has nothing with the platform and system

**Comment by rFlex** [comment]
It's due to some changes with CoreImage on iOS 9, I think I found out what's going on, will publish an update probably today.

**Comment by fayhot** [comment]
@rFlex 
Yeah, you're right.

I did a further test on the iphone 4s (iOS 8.4.1) , the memory gone well.

**Comment by ustbenchan** [comment]
@rFlex 

Any update on the fix?

**Comment by mjgaylord** [comment]
@ustbenchan do you know if this issue is still happening on iOS 9.1?

**Comment by ustbenchan** [comment]
I haven't get a iOS 9.1 device yet, but I guess it still happens.

Do you know which part of the CoreImage changed that leading to this problem?

**Comment by mjgaylord** [comment]
I am not entirely sure but it seems that a lot has changed in ios9 under the hood which has caused a few issues with SCRecorder. I am struggling with a crash when a delegate gets cleaned up in a video output, which seems like a bug in iOS9, that's why I thought your issue might be resolved in 9.1. 




I still have to test mine too.

**Comment by mjgaylord** [comment]
It looks like this was fixed in iOS 9.1 beta3: https://forums.developer.apple.com/message/50981#50981

**Comment by hlineholm** [comment]
I can confirm that this bug still exists on iOS 9.2. [https://forums.developer.apple.com/thread/17142](https://forums.developer.apple.com/thread/17142)

**Comment by tc-diamond** [comment]
the issue is still actual on iOS 9.2

**Comment by acushway** [comment]
Yeah, I just noticed this myself today. Core Image is leaking memory like crazy on iOS 9.2.1 and I can't find a way to get it to release it. Previously on 9.0 I think you could release the memory by replacing your cope image context with a new one and allowing your old one to be deallocated but that isn't working now. I've filed a radar: 24850067

**Comment by mitchellporter** [comment]
@acushway have you made any progress on this? I have an annoying issue where after the user records their video, the video comes out black. If I switch from using EAGL to Metal it will happen less frequently, but it still happens too often.

It happens on both iPhone 6 and 6 Plus, more often on the 6 Plus. I can't reproduce the issue on an iPhone 5 running iOS 8.4.

I'm basically setting a filter on the `videoConfiguration` property of the `SCRecorder` instance, so that the filter is applied to the video as the user is recording it.
